select * from Customer_Behaviour


-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender , SUM(purchase_amount) AS Total_Revenue
from Customer_Behaviour
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, discount_applied 
FROM Customer_Behaviour 
WHERE discount_applied = 'Yes' AND purchase_amount >= 
(SELECT AVG(purchase_amount) 
FROM Customer_Behaviour )


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating" 
FROM Customer_Behaviour
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5 


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type,  ROUND(AVG(purchase_amount::numeric), 2) 
FROM Customer_Behaviour
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
COUNT(customer_id) AS "Customer_id",
ROUND(AVG(purchase_amount::numeric), 2) AS Average_Revenue,
ROUND(SUM(purchase_amount::numeric), 2) As Total_Revenue
FROM Customer_Behaviour
GROUP BY subscription_status
ORDER BY Total_Revenue , Average_Revenue DESC


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS discount_rate
FROM Customer_Behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
FROM Customer_Behaviour
)

SELECT customer_segment, COUNT(*) as "Number of Customer"
FROM customer_type
GROUP BY customer_segment


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS(
	SELECT category,
		item_purchased,
		COUNT(customer_id) AS total_orders,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC) AS item_rank
	FROM Customer_Behaviour
	GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM Customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status

-- Q10. What is the revenue contribution of each age group?
SELECT "age_group ",
    SUM(purchase_amount) AS total_revenue
FROM Customer_Behaviour
GROUP BY "age_group "
ORDER BY total_revenue desc;

